#!/bin/bash

INPUT="/dev/video0"
NAME="dash"

print_usage() {
    echo "Usage:"
    echo "$0 -i <input>"
    echo "  -i path to input, default: $INPUT"
    echo "  -n name of the broadcast, default: $NAME"
    echo "  -h print this help"
}

while getopts "i:n:h" flag; do
    case "${flag}" in
        i) INPUT="${OPTARG}" ;;
        n) NAME="${OPTARG}" ;;
        h) print_usage 
            exit 0 ;;
        *) print_usage
            exit 0 ;;
    esac
done

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-info}"
export RUST_BACKTRACE="${RUST_BACKTRACE:-full}"

cargo run --bin moq-pub -- dash --name "$NAME" --input "$INPUT" --output "../media/$NAME" https://localhost:4443